/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Coin = IDL.Variant({
  'BNB' : IDL.Null,
  'BTC' : IDL.Null,
  'ETH' : IDL.Null,
  'SOL' : IDL.Null,
});
export const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Trade = IDL.Record({
  'direction' : Direction,
  'coin' : Coin,
  'profitLoss' : IDL.Float64,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
});
export const PortfolioView = IDL.Record({
  'tradeHistory' : IDL.Vec(Trade),
  'holdings' : IDL.Vec(IDL.Tuple(Coin, IDL.Float64)),
  'cashBalance' : IDL.Float64,
  'automatedTradingEnabled' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLivePrice' : IDL.Func([Coin], [IDL.Float64], []),
  'getPortfolioStats' : IDL.Func([], [PortfolioView], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetPortfolio' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleAutomatedTrading' : IDL.Func([], [], []),
  'trade' : IDL.Func([Coin, Direction, IDL.Float64], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Coin = IDL.Variant({
    'BNB' : IDL.Null,
    'BTC' : IDL.Null,
    'ETH' : IDL.Null,
    'SOL' : IDL.Null,
  });
  const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Trade = IDL.Record({
    'direction' : Direction,
    'coin' : Coin,
    'profitLoss' : IDL.Float64,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const PortfolioView = IDL.Record({
    'tradeHistory' : IDL.Vec(Trade),
    'holdings' : IDL.Vec(IDL.Tuple(Coin, IDL.Float64)),
    'cashBalance' : IDL.Float64,
    'automatedTradingEnabled' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLivePrice' : IDL.Func([Coin], [IDL.Float64], []),
    'getPortfolioStats' : IDL.Func([], [PortfolioView], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetPortfolio' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleAutomatedTrading' : IDL.Func([], [], []),
    'trade' : IDL.Func([Coin, Direction, IDL.Float64], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };